name: Linux Distribution Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  echo_hello_world_isaac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Verifica a distribuição do Linux
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cat /etc/*-release  # Comandos para Linux
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            sw_vers
          else
            echo "Sistema Operacional não suportado"
          fi
